on load:
  set {Prefix} to "&6Oyunbaz &8➠"
  set {Motd_Server} to " &8➥ &7Oyunbaz Network &f&l&m-&r &8[&f1.8 &8- &f1.10&8]  &e&lHEMEN KATIL!      &e▶ &f{GUNCELLEME} &e◀" 
  set {HaberAyarlandi} to "&aHaber ayarlandı:&7 "
  set {HaberSilindi} to "&7Mevcut haber sıfırlandı."
  set {Iznin_Yok} to "&7Bunun için iznin yok."
  set {Cok_Uzun} to "&7Girdiğin mesaj çok uzun."
  set {Lobi_Dunyasi} to "world"
